### ISSUE TITLE
Change how module is executed on the minions

### ISSUE THREAD

**Issue by neilmunday** [neilmunday/Salt-Minion-Inventory#22]
Instead of invoking the inventory.audit function every few hours, implement "inventory.run" to execute every 10-15 minutes. This function should read the config files on the minion (see issue #21) to determine which functions need to be executed.

Proposed functions to run regularly:

- audit -> existing audit functionality minus logging user info
- user -> new function to report users currently logged into a minion
- metrics -> new function to report back metrics for the minion (e.g. CPU load, memory use, disk usage etc.)

**Comment by redonkuless** [comment]
trying to find where to post this, or message you, audit fails on windows or at least Windows Server 2012R2 + Server 2016, grain biosreleasedate is not supported on windows.

[DEBUG   ] return event: {u'24': {u'jid': u'20190930151650113739', u'retcode': 1, u'ret': u'The minion function caused an exception: Traceback (most recent call last):\n  File "c:\\salt\\bin\\lib\\site-packages\\salt\\minion.py", line 1663, in _thread_return\n    return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)\n  File "c:\\salt\\bin\\lib\\site-packages\\salt\\executors\\direct_call.py", line 12, in execute\n    return func(*args, **kwargs)\n  File "c:\\salt\\var\\cache\\salt\\minion\\extmods\\modules\\inventory.py", line 66, in audit\n    properties[p] = grains[p]\n  File "c:\\salt\\bin\\lib\\site-packages\\salt\\utils\\context.py", line 236, in __getitem__\n    return self._dict()[key]\nKeyError: \'biosreleasedate\'\n', u'out': u'nested'}}
[DEBUG   ] LazyLoaded nested.output
24:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1663, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "c:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "c:\salt\var\cache\salt\minion\extmods\modules\inventory.py", line 66, in audit
        properties[p] = grains[p]
      File "c:\salt\bin\lib\site-packages\salt\utils\context.py", line 236, in __getitem__
        return self._dict()[key]
    KeyError: 'biosreleasedate'
